version: '2.2'

services:      
  ng-pokedex-build:
    build:
      context: .
      dockerfile: ./.docker/build.dockerfile
    command: ng serve --host 0.0.0.0
    container_name: ng-pokedex-build-start
    image: ng-pokedex-build
    networks:
      - dev-network
    ports:
      - '4200:4200'
      
  ng-pokedex-test:
    build:
      context: .
      dockerfile: ./.docker/tests.dockerfile
    command: /bin/bash
    container_name: ng-pokedex-test-start
    image: ng-pokedex-test

  ng-pokedex-lint:
    command: /bin/bash /pokedex/scripts/run.sh lint
    container_name: ng-pokedex-lint-start
    image: ng-pokedex-test
    volumes:
      - /artifacts:/artifacts
      
  ng-pokedex-unittest:
    command: /bin/bash /pokedex/scripts/run.sh unit
    container_name: ng-pokedex-unittest-start
    image: ng-pokedex-test
    volumes:
      - /artifacts:/artifacts

  ng-pokedex-e2etest:
    command: /bin/bash /pokedex/scripts/run.sh e2e
    container_name: ng-pokedex-e2etest-start
    image: ng-pokedex-test
    volumes:
      - /artifacts:/artifacts

  ng-pokedex-prod:
    build:
      context: .
      dockerfile: ./.docker/prod.dockerfile
    command: /bin/bash /pokedex/scripts/run.sh dist
    container_name: ng-pokedex-prod-start
    image: ng-pokedex-prod
    networks:
      - dev-network
    ports:
      - '4200:4200'
    volumes:
      - /artifacts:/artifacts

networks:
  dev-network:
    driver: bridge
