version: '2.2'

services:      
  ng-pokedex-client:
    build:
      context: .
      dockerfile: ./.docker/build.dockerfile
    command: ng serve --host 0.0.0.0
    container_name: ng-pokedex-client-start
    image: ng-pokedex-client
    networks:
      - dev-network
    ports:
      - '4200:4200'
    volumes:
      - .:/pokedex
      
  ng-pokedex-test:
    build:
      context: .
      dockerfile: ./.docker/tests.dockerfile
    command: /bin/bash
    container_name: ng-pokedex-test-start
    image: ng-pokedex-test
    volumes:
      - .:/pokedex

#  ng-pokedex-base:
#    build:
#      context: .
#      dockerfile: ./.docker/base.dockerfile
#    command: /bin/bash
#    container_name: ng-pokedex-base-start
#    image: ng-pokedex-base
#    volumes:
#      - .:/pokedex
      
networks:
  dev-network:
    driver: bridge
